name: Mimicode-CustomRestartTitle
version: '${project.version}'
main: com.top1.mimicodecustomrestarttitle.Main
api-version: 1.13
author: MimiCode
website: dsc.gg/mimicode
description: Plugin na custom title dla gracza podczas restarotwania serwera!

commands:
  restarttitle:
    description: jajo